#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="# [ 310 ] While trying to create a file on replicate with write behind set-up, client crashes"
comments="# [ 310 ] While trying to create a file on replicate with write behind set-up, client crashes"

source ../../init

start_glusterfs


cd $MOUNTDIR/client1

touch dot 2> tmpfile

if [ $(grep "Transport endpoint not connected" tmpfile | wc -l) -ne 0 ];then
  not_ok $description
  comment $comments
else    
  ok $description
fi

rm tmpfile
## Testcase End
cleanup_glusterfs
