#!/bin/bash

description="# Incorrect PID printed in the glusterfs log header"
comments="# The log header prints the pre-daemon pid which does not match the pid seen if we do a ps."


source ../../init

start_glusterfs --no-servers --no-clients

sleep 2

$($GLUSTERFS --run-id regr.c.$BUGID -f $SPECDIR/server1.vol -l $LOGDIR/$(hostname)-server1.log --pid-file=$PWD/server1.pid)


if [ $(cat server1.pid) == $(cat $LOGDIR/$(hostname)-server1.log | grep PID | cut -d":" -f2) ] ; then
        ok $description
        comment $comments
else
    not_ok $description
    comment $comments
fi


cleanup_glusterfs

rm *.pid >/dev/null
