#!/bin/bash

description="# Mount command should mimic existing practice"
comments="# It is more intuitive for unix sysadmin to have glusterfs <server>:<path> /mnt/point"

source ../../init
start_glusterfs --no-servers --no-clients

sleep 5

mount -t glusterfs 127.0.0.1:$SPECDIR/client1 $MOUNTDIR/client1 2> tmpfile
if [ $(grep "unknown volfile server port" tmpfile | wc -l) -ne 0 ];then
	not_ok $description
	comment $comments
else
	ok $description
fi

rm tmpfile
cleanup_glusterfs