#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="# Mount command should mimic existing practice"
comments="# It is more intuitive for unix sysadmin to have glusterfs <server>:<path> /mnt/point"

source ../../init
start_glusterfs --no-servers --no-clients

sleep 5

mount -t glusterfs 127.0.0.1:$SPECDIR/client1 $MOUNTDIR/client1 2> tmpfile
if [ $(grep "unknown volfile server port" tmpfile | wc -l) -ne 0 ];then
	not_ok $description
	comment $comments
else
	ok $description
fi

rm tmpfile
cleanup_glusterfs
