#!/bin/bash

description="# (117) Wrong command line does not throw error"
comments="# Whenever glusterfs is not started, exit status should not be 0" 

source ../../init

start_glusterfs --no-clients

$GLUSTERFS -f $SPECDIR/client1.vol $LOGDIR/$(hostname)-client1.log $MOUNTDIR/client1 2> /dev/null

if [ $? -ne 0 ];then
    not_ok $description
    comment $comments
else
    ok $description
fi

cleanup_glusterfs