#!/bin/bash

#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.


source ./init
source ./regression_helpers

GLUSTERD_DIR=$(dirname $GLUSTERD);

mkdir $EXPORT_DIR/$global_bug_id;

#testcase starts here

#Export directories should be from $EXPORT_DIR/$global_bug_id directory.

#Mount point also should be from $EXPORT_DIR/$global_bug_id directory.

#Starting the volume, mounting it and checking for the appropriate
#functionality comprises the testcase.

#This is my testcase

#testcase ends here

test_kill;

test_cleanup;


