#!/bin/bash

description="# (143) Mysterious lost chown call"
comments="# Fix will be by adding setattr() fop to glusterfs."

source ../../init

start_glusterfs 

gcc -o ctestfun ctestfun.c
./ctestfun $MOUNTDIR/client1/1

if [ $? -ne 0 ];then
    not_ok $description
    comment $comments
else
    ok $description
fi

cleanup_glusterfs
