#!/bin/bash

description="# In stripe client crashes when disk space is full"
comments="# When mknod system call is executed on a disk which is full with S_IFREG client crashes "

source ../../init

start_glusterfs 

sleep 5

gcc $SPECDIR/mknod.c -o $SPECDIR/mkn
$SPECDIR/mkn $MOUNTDIR/client1/foo 
if [ $? -ne 0  ]; then
    not_ok $description
    comment $comments
else
    ok $description
    comment $comments
fi

rm $SPECDIR/mkn

cleanup_glusterfs