#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="#[ glusterfs 2.0.2 ] - No error logged on stdout/stderr upon missing mount point during client invocation"
comments="#error should be displayed on the sreen"

source ../../init

start_glusterfs --no-clients

$($GLUSTERFS --run-id regr.c.$BUGID -f $SPECDIR/client1.vol -l $LOGDIR/$(hostname)-client1.log)
if [ $? -ne 0 ]
then
       ok $description 
else
       not_ok $description
       comment $comments
fi
        
cleanup_glusterfs
