#!/bin/bash

description="#[ glusterfs 2.0.2 ] - No error logged on stdout/stderr upon missing mount point during client invocation"
comments="#error should be displayed on the sreen"

source ../../init

start_glusterfs --no-clients

$($GLUSTERFS --run-id regr.c.$BUGID -f $SPECDIR/client1.vol -l $LOGDIR/$(hostname)-client1.log)
if [ $? -ne 0 ]
then
       ok $description 
else
       not_ok $description
       comment $comments
fi
        
cleanup_glusterfs
