#!/bin/bash

description="# (131) provide a way to get the file location in clustered storage"
comments="#doesn't have a mechanism to get the location of the file"

source ../../init

start_glusterfs 

sleep 5
if [ $(getfattr -d -e hex -m "trusted.glusterfs.location" $MOUNTDIR/client1 2> /dev/null | wc -l) -ne 0 ];then
	ok $description
else
	not_ok $desrciption
	comment $comments
fi

cleanup_glusterfs
