#!/bin/bash

description="# (26) Version mismatch not handled correctly"
comments="# Tried connecting 2.0.2 client with different version server"

source ../../init

start_glusterfs --no-clients

/opt/glusterfs/2.0.2/sbin/glusterfs -f $SPECDIR/client1.vol -l $LOGDIR/$(hostname)-client1.log $MOUNTDIR/client1 

sleep 5

for var in `seq 1 100`; do
	ls $MOUNTDIR/client1 2> tmpfile 
	if [ $(grep "Transport endpoint is not connected" tmpfile | wc -l) -ne 0 ];then
		not_ok $description
		comment $comments
		break
	fi  
done
rm tmpfile

[ $var -eq 100 ] && ok $description

umount -l $MOUNTDIR/client1
cleanup_glusterfs
