#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="# (26) Version mismatch not handled correctly"
comments="# Tried connecting 2.0.2 client with different version server"

source ../../init

start_glusterfs --no-clients

/opt/glusterfs/2.0.2/sbin/glusterfs -f $SPECDIR/client1.vol -l $LOGDIR/$(hostname)-client1.log $MOUNTDIR/client1 

sleep 5

for var in `seq 1 100`; do
	ls $MOUNTDIR/client1 2> tmpfile 
	if [ $(grep "Transport endpoint is not connected" tmpfile | wc -l) -ne 0 ];then
		not_ok $description
		comment $comments
		break
	fi  
done
rm tmpfile

[ $var -eq 100 ] && ok $description

umount -l $MOUNTDIR/client1
cleanup_glusterfs
