#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="# testing/features/trashcan crashes server"
comments="#the actual bug.... After deleting a file, if you browse to the trashcan and delete it again, the server crashes."

source ../../init

start_glusterfs

sleep 5

touch $MOUNTDIR/client1/test1 && rm $MOUNTDIR/client1/test1
for var in `seq 1 100`; do
	rm $MOUNTDIR/client1/.trashcan/test1 2> /dev/null
        if [ $? -ne 0 ];then
                not_ok $description
                comment $comments
                break
        fi
done

[ $var -eq 100 ] && ok $description

cleanup_glusterfs
