#!/bin/bash

description="# testing/features/trashcan crashes server"
comments="#the actual bug.... After deleting a file, if you browse to the trashcan and delete it again, the server crashes."

source ../../init

start_glusterfs

sleep 5

touch $MOUNTDIR/client1/test1 && rm $MOUNTDIR/client1/test1
for var in `seq 1 100`; do
	rm $MOUNTDIR/client1/.trashcan/test1 2> /dev/null
        if [ $? -ne 0 ];then
                not_ok $description
                comment $comments
                break
        fi
done

[ $var -eq 100 ] && ok $description

cleanup_glusterfs