#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

bugid=$(pwd | cut -d '/' -f 4)

description="# ($bugid) auth.login and auth.addr cannot be used in conjunction with each other"
comments="# It is addr only authentication when both login & addr are both specified"

source ../../init
start_glusterfs

sleep 5

if [ $(mount | grep "$MOUNTDIR/client1" | wc -l) -ne 0 ];then
	not_ok $description
	comment $comments
else
 	ok $description
fi

cleanup_glusterfs
