#!/bin/bash
#
#  Copyright (c) 2006-2010 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="# (579) write-behind cache-size less than 128KB leads to error"
comments="write-behind cache-size less than 128KB leads to error"

source ../../init

start_glusterfs

if [ $( grep  'cannot be more than window-size(131072)' $LOGDIR/$(hostname)-client1.log | wc -l ) -ne 0 ]
then
    not_ok $description
    comment $comments
else
    ok $description
fi

cleanup_glusterfs