#!/bin/bash

description="#mkdir fails"
comments="#mkdir after rm of regular file of same name fails"

source ../../init

start_glusterfs --no-servers --no-clients

## Testcase START
if [ ! -f /sbin/mount.glusterfs-$VERSION ]; then
     sed -e 's/^\(\s*prefix=\)".*"/\1"\/opt\/glusterfs\/'$VERSION'"/; s/^\(\s*cmd_line=.*\/sbin\/\).*/\1glusterfs");/' /sbin/mount.glusterfs > /sbin/mount.glusterfs-$VERSION
     chmod +x /sbin/mount.glusterfs-$VERSION
fi  

cd $MOUNTDIR

touch dot
rm -rf dot
mkdir dot 2> tmpfile

if [ $(grep "File exists" tmpfile | wc -l) -ne 0 ];then
  not_ok $description
  comment $comments
else    
  ok $description
fi

rm tmpfile
## Testcase End

cleanup_glusterfs
