#!/bin/bash

description="#  Bug 445  -  Transport endpoint is not connected "
comments="# Touching a file works,  writing actual data to it doesn't."


source ../../init

start_glusterfs 

sleep 2
echo "this is file content" >  $MOUNTDIR/client1/testing.txt 

retval=$?



if [ $retval -eq 0 ]
then
 ok $description
        comment $comments

else
 not_ok $description
        comment $comments

fi


rm $MOUNTDIR/client1/testing.txt >/dev/null
cleanup_glusterfs

