#!/bin/bash

description="#  Bug 172 -  Cannot open -  on tar extraction "
comments="# trying to run kernel_compile tar extraction"


source ../../init

start_glusterfs 

sleep 2
cd  $MOUNTDIR

mkdir txt

for i in {1..1000}
do

(dd if=/dev/zero of=$MOUNTDIR/txt/$i.txt bs=4kB count=25) 2> /dev/null
done



tar -cf file.tar txt/* 2> /dev/null
retval1=$?

tar -xf file.tar 2> /dev/null

retval2=$?



if [ $retval1 -eq 0 ] && [ $retval2 -eq 0 ]
then
 ok $description
        comment $comments

else
 not_ok $description
        comment $comments

fi


rm $MOUNTDIR/file.tar >/dev/null

rm -rf $MOUNTDIR/txt > /dev/null

cleanup_glusterfs

