#!/bin/bash

description="# (241) GlusterFS not honouring SETGID flag"
comments="# setgid problem on glusterfs mount"

source ../../init
start_glusterfs

sleep 5
cd $MOUNTDIR/client1
mkdir 1
chgrp avahi 1
chmod g+s 1
var1=$(ls -ld 1 | cut -d " " -f 4)
cd 1
mkdir 2
var2=$(ls -ld 2 | cut  -d " " -f 4)

#echo $var1
#echo $var2

if [ $var1 = $var2 ];then
	ok $description
else
	not_ok $description
	comment $comments
fi

rmdir $MOUNTDIR/client1/1/2
cd ..
rmdir $MOUNTDIR/client1/1
cd `dirname $MOUNTDIR`

cleanup_glusterfs
