#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="# (241) GlusterFS not honouring SETGID flag"
comments="# setgid problem on glusterfs mount"

source ../../init
start_glusterfs

sleep 5
cd $MOUNTDIR/client1
mkdir 1
chgrp avahi 1
chmod g+s 1
var1=$(ls -ld 1 | cut -d " " -f 4)
cd 1
mkdir 2
var2=$(ls -ld 2 | cut  -d " " -f 4)

#echo $var1
#echo $var2

if [ $var1 = $var2 ];then
	ok $description
else
	not_ok $description
	comment $comments
fi

rmdir $MOUNTDIR/client1/1/2
cd ..
rmdir $MOUNTDIR/client1/1
cd `dirname $MOUNTDIR`

cleanup_glusterfs
