#!/bin/bash

source ./regression_helpers
source ./init

GLUSTERD_DIR=$(dirname $GLUSTERD);

mkdir $EXPORT_DIR/$global_bug_id/;

$GLUSTERD_DIR/gluster volume create vol $(hostname):$EXPORT_DIR/$global_bug_id/export1 2>/dev/null 1>/dev/null;

$GLUSTERD_DIR/gluster --mode=script volume stop vol | grep "started state" 2>/dev/null 1>/dev/null;

if [ $? -ne 0 ]; then
    echo -n "$global_bug_id: "
    not_ok;
else
    echo -n "$global_bug_id: "
    ok;
fi

test_kill;

test_cleanup;

