#!/bin/bash

description="# (156) Broken symbolic link when relative path is given for a log file"
comments="# When glusterfs is started with giving relative path for the log file, the symbolic link is broken."

source ../../init

start_glusterfs --no-servers --no-clients

$GLUSTERFS --run-id bug-156 -f $SPECDIR/server1.vol -l ../regr/server11.log 

sleep 5

if [ $(ls -ltr server11.log | grep '../' | wc -l) -ne 0 ];then
    not_ok $description
    comment $comments
else
    ok $description
fi

rm server11.log* 2> /dev/null

cleanup_glusterfs

























































































