#!/bin/bash

description="# (28) Deleting a backend export directory in an AFR setup can cause a segfault while trying to self heal"
comments="# If the backend export directory is deleted, self heal tries to mkdir and while doing so accesses loc->parent which is NULL and segfaults."

source ../../init

start_glusterfs

sleep 5

rmdir $EXPORTDIR/export1
for var in `seq 1 100`; do
	ls $MOUNTDIR/client1 2> tmpfile
	if [ $(grep "Transport endpoint is not connected" tmpfile | wc -l) -ne 0 ];then
                not_ok $description
                comment $comments
                break
        fi
done
rm tmpfile

[ $var -eq 100 ] && ok $description

cleanup_glusterfs
