#!/bin/bash
#
#  Copyright (c) 2006-2010 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="# (574) Sticky bit files are not listed in the output of ls on a dht volume"
comments="Sticky bit files are not listed in the output of ls on a dht volume"

source ../../init

start_glusterfs

cp /bin/ksh $MOUNTDIR/client1

if [ $( ls -l $MOUNTDIR/client1 | wc -l ) -ne 0 ]
then
    ok $description
else
    not_ok $description
    comment $comments
fi

cleanup_glusterfs