#!/bin/bash

description="# (133) posix_getxattr doesn't handle 'glusterfs.content' key"
comments="#Supporting glusterfs.content key"

source ../../init

start_glusterfs

sleep 5
if [ $(getfattr -d -e hex -m "trusted.glusterfs.content" $MOUNTDIR/client1 2> /dev/null | wc -l) -ne 0 ];then
	ok $description
else
	not_ok $desrciption
	comment $comments
fi

cleanup_glusterfs
