#!/bin/bash

description="# (133) posix_getxattr doesn't handle 'glusterfs.content' key"
comments="#Supporting glusterfs.content key"

version=$1
bugid=$(pwd | cut -d '/' -f 4)

exportdir=/jbod/regr/$bugid
mountdir=/mnt/regr/$bugid/$version

function ok () {
  desc=$@
  echo "ok - $desc"
}

function not_ok () {
  desc=$@
  echo "not ok - $desc"
}


function comment () {
  desc=$@
  echo "$desc"
}

[ $# -ne 1 ] && {
  not_ok "#<Usage: $(basename $0) <glusterfs_version>"
  exit 
}


/opt/qa/regr/setup $version $bugid

sleep 5
if [ $(getfattr -d -e hex -m "trusted.glusterfs.content" $mountdir/client1 2> /dev/null | wc -l) -ne 0 ];then
	ok $description
else
	not_ok $desrciption
	comment $comments
fi

/opt/qa/regr/cleanup $version $bugid
