#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.


description="# [ 339 ] glusterfsd fails to start when there are no active interfaces having address in the address family configured"
comments="# [ 339 ] glusterfsd fails to start when there are no active interfaces having address in the address family configured"

source ../../init

start_glusterfs --no-clients

LOG_MSG=$(tail  $LOGDIR/$(hostname)-server1.log | grep 'glusterfs: Successfully started' | wc -l)


if [ $LOG_MSG -eq 0 ]; then
    not_ok $description
    comment $comments
else 
   ok $description
fi

cleanup_glusterfs 