#!/bin/bash

description="# (313) rename is broken"
comments="#when try to rename a file using mv it fails"

source ../../init
start_glusterfs

sleep 10;

touch $MOUNTDIR/client1/tmp1.txt
mv $MOUNTDIR/client1/tmp1.txt $MOUNTDIR/client1/tmp2.txt 2> tmpfile

if [ $(grep "Structure needs cleaning" tmpfile | wc -l) -ne 0 ];then
    not_ok $description
    comment $comments
else 
    ok $description
fi

rm tmpfile
cleanup_glusterfs
