#!/bin/bash
#
#  Copyright (c) 2006-2009 Gluster, Inc. <http://www.gluster.com>
#  This file is part of GlusterFS.
#
#  GlusterFS is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published
#  by the Free Software Foundation; either version 3 of the License,
#  or (at your option) any later version.
#
#  GlusterFS is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see
#  <http://www.gnu.org/licenses/>.

description="# (313) rename is broken"
comments="#when try to rename a file using mv it fails"

source ../../init
start_glusterfs

sleep 10;

touch $MOUNTDIR/client1/tmp1.txt
mv $MOUNTDIR/client1/tmp1.txt $MOUNTDIR/client1/tmp2.txt 2> tmpfile

if [ $(grep "Structure needs cleaning" tmpfile | wc -l) -ne 0 ];then
    not_ok $description
    comment $comments
else 
    ok $description
fi

rm tmpfile
cleanup_glusterfs
